### ISSUE TITLE
BCpie captcha version 2

### ISSUE THREAD

**Issue by developerside** [onecreative/bcpie#1]
BCpie captcha version 2 validation {module_recaptcha version="2"} is not validating but when i use 
{module_recaptcha} it validates do you have an updated script?

**Comment by onecreative** [comment]
@developerside Sorry for the slow response. I'll check this out tomorrow.

**Comment by developerside** [comment]
any news?

**Comment by onecreative** [comment]
@developerside This has just been fixed. Thanks for reminding me.

**Comment by logopogo** [comment]
I never had an issue with captchaV2 validating previously, but with this update, it no longer validates anymore???

**Comment by onecreative** [comment]
@logopogo I'm assuming you are referring to the fact that recaptcha v2 doesn't show an error message below it anymore. Is that correct? If so, that was intended. It has its own way of showing errors, so I just made it submittable if the captcha was accepted, and not submittable if it was rejected.

**Comment by logopogo** [comment]
Yep, your assumption is correct.
But recaptcha v2 doesn't show any errors for form validation (ie: if it's not ticked/attempted at all). So now there appears to be no UI feedback to draw a users attention to it like there is for other required form elements. Can we still add this?

**Comment by onecreative** [comment]
That’s a good point. My perspective was that Recaptcha is used at the end of a form, and that it is well recognized as something that needs to be done, and it tells you to do it, so that would be enough. But I suppose that perspective might be a bit limited.

**Comment by logopogo** [comment]
Yeah, I wouldn't agree that recaptcha is well recognised - and to some, it's probably very confusing as to what it is/does. Only that it's extremely easy to complete does it work so well. I think when it comes to UI/UX (especially in forms) we need as many visual cues as feasibly possible - or at least have the option to implement them.

**Comment by onecreative** [comment]
@logopogo I just reopened this. I'll make that adjustment.

**Comment by onecreative** [comment]
@logopogo I've made recaptcha show a validation response on submit. It won't do any live validation  on interaction though. I'm going to have to figure that one out, since I'm competing with BC's inline scripts.

A note about a breaking change that I made: Validation classes and elements are different in this version. This is a change I've been wanting to make for a while. The new options for this area are as follows:

`'validationGroupElement' : 'div',` _// the default parent element to receive the validationGroupClass. It will be the closest matching parent._

`'validationGroupClass' : 'validation-group',`

`'validationMessageElement' : 'small',`

`'validationMessageClass' : 'validation-message',`

`'validationInputClass' : 'validation-input',`

`'errorClass' : 'error',`

`'validClass' : 'valid',`

I like wrapping the input in its label element and setting validationGroupElement to 'label'. You can also specify the validationGroupElement for individual fields by adding `data-validation-group="my chosen element"` to your input.
